logging:
    version: 1
    formatters:
        simple:
            format: "%(name)s\t%(levelname)s\t%(asctime)s\t%(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    loggers:
        processing:
            level: DEBUG
            handlers: [console]
            propagate: no
        model_management:
            level: DEBUG
            handlers: [console]
            propagate: no
        util:
            level: DEBUG
            handlers: [console]
            propagate: no
    root:
        level: DEBUG
        handlers: [console]